#!/usr/bin/env bash

set -eu

echo "Creating pypirc file in ...."

# shellcheck disable=SC2129
echo -e "[pypi]" >> ~/.pypirc
echo -e "username = __token__" >> ~/.pypirc
echo -e "password = $PYPI_API_TOKEN" >> ~/.pypirc

echo "pypirc ...."
cat ~/.pypirc

# Repo by default on twine is pypi.org, $PYPI_API_TOKEN should be set in circle.
echo "Building...."
python3 setup.py sdist bdist_wheel
echo "Uploading...."
python3 -m twine upload -u mkeshav dist/*
