#!/usr/bin/env bash

set -eu
PROJECT_NAME="pacemaker"
echo "Creating pypirc file in ...."

# shellcheck disable=SC2129
echo -e "[$PROJECT_NAME]" >> ~/.pypirc
echo -e " repository = https://upload.pypi.org/legacy/" >> ~/.pypirc
echo -e " username = __token__" >> ~/.pypirc
echo -e " password = $PYPI_API_TOKEN" >> ~/.pypirc

# Repo by default on twine is pypi.org, $PYPI_API_TOKEN should be set in circle.
echo "Building...."
python3 setup.py sdist bdist_wheel
echo "Uploading...."
python3 -m twine upload --repository PROJECT_NAME dist/*
